import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import config from "@/config/config";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
  keywords: "Shop online"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="bg-primary-500 dark:bg-zinc-900 py-3 w-full flex ">
          <div className="container mx-auto flex justify-between items-center"> 
            <h1 className="text-white font-extrabold text-xl">LOGO</h1>
            <Navbar />
          </div>
        </header> */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
